[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build --workspace=apps/cc-backend"]

[start]
cmd = "cd apps/cc-backend && node dist/main.js"
