[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x", "postgresql"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run build --workspace=packages/core",
  "npm run build --workspace=packages/adapters",
  "cd apps/cc-backend && npm run prisma:generate",
  "cd apps/cc-backend && npm run build"
]

[start]
cmd = "cd apps/cc-backend && npx prisma migrate deploy --schema=../../prisma/schema.prisma && node dist/main.js"
